[unix]
backend = "x86"
intermediate = "build/ir.asm"
stdlib = ""
assemble = "nasm -f elf64 -o build/obj.o build/ir.asm"
link = "ld build/obj.o -o a.out" # ld is not gonna work here because stdc needs libc init
interpret = "./a.out"
