#include <stdlib.h>
#include <stdio.h> // DO NOT USE printf(), doesnt work with NASM64 for some reason (probably variadic args)
#include <stddef.h>

void dryft_push(size_t);
size_t dryft_pop();
void dryft_main();


// generated by claude code because AI is the future or whatever
void __size_t_to_string(size_t num, char *buf) {
    if (num == 0) {
        buf[0] = '0';
        buf[1] = '\0';
        return;
    }
    
    int i = 0;
    size_t temp = num;
    
    // Count digits
    while (temp > 0) {
        temp /= 10;
        i++;
    }
    
    buf[i] = '\0';
    
    // Fill buffer in reverse
    while (num > 0) {
        buf[--i] = '0' + (num % 10);
        num /= 10;
    }
}


void c_print_string() {
	char* a = (char*) dryft_pop();
	puts(a);
}

void c_print_int() {
	// dynamic allocation is not necessary, I used it to test if stdlib works fine
	size_t a = dryft_pop();
	char* buf = (char*) malloc(512);
	__size_t_to_string(a, buf);
	puts(buf);
	free((void*) buf);
}

int main() {
	dryft_main();
	return 0;
}