/*
* Copyright (C) 2025 Filip Chovanec
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/


use std::process::Command;
use std::env;
use std::io;
use std::io::Write;
use std::fs;
use clap::{Parser, ValueEnum};
use std::path::{Path, PathBuf};

use serde::Deserialize;
use toml;

pub mod backends;
pub mod frontend;

use backends::c99::C99Backend;
use backends::Backend;

type DefaultBackend = C99Backend;

fn repl(targetspec: TargetSpec) {
    // temporary disable, behavior on NASM is a bit different
    if targetspec.backend == "NASM64" {
        panic!("NASM64 unsupported for repl currently");
    }
    
    loop {
        print!("Dryft repl> ");
        io::stdout().flush().unwrap();   // flush so it appears immediately
        let mut input = String::new();
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
        if input.trim().is_empty() {
            continue;
        }

        match input.trim() {
            /*"#open" => {
                let mut fname = String::new();  
                io::stdin()
                    .read_line(&mut fname)
                    .expect("Failed to read line");
                rbr(fname.trim());
            }*/
            ".help" | "help" => {
                println!(".help/help  => display this screen");
                println!(".exit/.quit => leave the REPL, terminating this process");
            }
            ".exit" | ".quit" => {
                break
            }
            _ => {
                let src = format!("act: main {} ;", input);
                let mut backend = crate::backends::select(&targetspec.backend);
                fs::write(&targetspec.intermediate, frontend::compile_full(backend, &src)).unwrap();
                if let Err(e) = externalize(&targetspec.externalize) {
                    println!("{}", e);
                } else {
                    interpret(targetspec.interpret.clone().unwrap().as_ref());
                }
            }
        }
    }
}

fn build_file(inp: &Path, out: &Path, backend_name: &str) {
    let src = &String::from_utf8(fs::read(inp).unwrap_or("".into())).unwrap();
    if src.is_empty() {
        println!("Nothing to compile :/");
    } else {
        let mut backend = crate::backends::select(backend_name);
        fs::write(out, frontend::compile_full(backend, src)).unwrap();   
    }
}

// pass IR generated by dryftc into an external compiler, like gcc or llvm
fn externalize(cmd: &str) -> Result<(), String> {
    let (_, stderr) = bash(cmd);
    if !stderr.is_empty() {
        return Err(stderr)
    }
    return Ok(())
}

// execute step after externalize(), necessary for VM-based backends
// TODO: currently waits for finish to disply stdout, which is not good for interactive apps. Start a proper process in future.
fn interpret(cmd: &str) {
    let (stdout, _) = bash("./a.out");
    println!("{}", stdout);  
}

// returns stdout and stderr post cmd execution
fn bash(cmd: &str) -> (String, String) {
    let output = Command::new("bash")
        .arg("-c")
        .arg(cmd)
        .output()
        .expect("Failed to execute bash");
    (String::from_utf8_lossy(&output.stdout).to_string(), String::from_utf8_lossy(&output.stderr).to_string())
}

#[derive(Deserialize)]
struct TargetDesc { 
    // only provides linux support for now, windows/mac support in the future
    unix: Option<TargetSpec>,
    windows: Option<TargetSpec>,
}

// platform independent
#[derive(Deserialize)]
struct TargetSpec {
    dependencies: Vec<String>, // binaries used by the below
    intermediate: PathBuf, // file to write dryftc output to
    externalize: String, // command describing how to use an external compiler to finalize compilation. 
    interpret: Option<String>, // command to run the final product. If none, use default system execute function (TODO)
    linkstep: Option<String>,
    backend: String,
}   

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct Cli {
    pub inputfile: Option<PathBuf>,

    #[arg(short = 't', long = "target")]
    #[arg(default_value = "cc" )]
    /// One of the targets defined in src/targets/
    pub target: String,

    /// only outputs the final dryftc assembly, no external tooling will be called
    #[arg(long = "assembly-only")]
    pub assembly_only: bool,

    /// output file where the dryftc assembly will be stored
    #[arg(short = 'a', long = "assembly-out")]
    pub assembly_out: Option<PathBuf>,
}

fn main() {
    let cli = Cli::parse();

    let target_name = cli.target; 
    let target_raw = String::from_utf8(fs::read(&format!("src/targets/{target_name}.toml")).expect("Unknown target")).expect("Bad utf8 in target description");
    let target_toml: TargetDesc = toml::from_str(&target_raw).expect("Invalid target description");
    
    // TODO: add external dependency checks

    let mut targetspec = match env::consts::FAMILY {
        "unix" => target_toml.unix.expect("Your platform (UNIX) does not yet support this target"),
        "windows" => target_toml.windows.expect("Your platform (WINDOWS) does not yet support this target"),
        other => panic!("Unknown host OS family {other}"),
    };

    if let Some(a) = cli.assembly_out {
        targetspec.intermediate = a;
    }

    if let Some(f) = cli.inputfile {
        build_file(&f, &targetspec.intermediate, &targetspec.backend);
        if !cli.assembly_only {
            externalize(&targetspec.externalize).unwrap();
        }
    } else {
        repl(targetspec);
    }
}
